import { ArticleCardProps } from '../components/list/ArticleCard';

export const articleSample: ArticleCardProps[] = [
  {
    eyeCatch: 'image1.png',
    category: 'A',
    title: 'Article A',
    description: 'This is Article A',
    url: '/article/a',
  },
  {
    eyeCatch: 'image2.png',
    category: 'B',
    title:
      'Apple Intelligence、visionOS 2.4により本日からApple Vision Proで利用可能に',
    description: 'This is Article B',
    url: '/article/b',
  },
  {
    eyeCatch: 'image3.png',
    category: 'C',
    title:
      '画像がボックス外に出ないように画像がボックス外に出ないように画像がボックス外に出ないように画像がボックス外に出ないように画像がボックス外に出ないように',
    description:
      'This is ArticleC 画像がボックス外に出ないように画像がボックス外に出ないように画像がボックス外に出ないように画像がボックス外に出ないように',
    url: '/article/c',
  },
  {
    eyeCatch: 'image1.png',
    category: 'D',
    title: 'Article D',
    description: 'This is Article D',
    url: '/article/d',
  },
  {
    eyeCatch: 'image2.png',
    category: 'E',
    title: 'Article E',
    description: 'This is Article E',
    url: '/article/e',
  },
  {
    eyeCatch: 'image3.png',
    category: 'F',
    title: 'Article F',
    description: 'This is Article F',
    url: '/article/f',
  },
  {
    eyeCatch: 'image1.png',
    category: 'G',
    title: 'Article G',
    description: 'This is Article G',
    url: '/article/g',
  },
  {
    eyeCatch: 'image2.png',
    category: 'H',
    title: 'Article H',
    description: 'This is Article H',
    url: '/article/h',
  },
  {
    eyeCatch: 'image3.png',
    category: 'I',
    title: 'Article I',
    description: 'This is Article I',
    url: '/article/i',
  },
  {
    eyeCatch: 'image1.png',
    category: 'J',
    title: 'Article J',
    description: 'This is Article J',
    url: '/article/j',
  },
  {
    eyeCatch: 'image2.png',
    category: 'K',
    title: 'Article K',
    description: 'This is Article K',
    url: '/article/k',
  },
  {
    eyeCatch: 'image3.png',
    category: 'L',
    title: 'Article L',
    description: 'This is Article L',
    url: '/article/l',
  },
  {
    eyeCatch: 'image1.png',
    category: 'M',
    title: 'Article M',
    description: 'This is Article M',
    url: '/article/m',
  },
  {
    eyeCatch: 'image2.png',
    category: 'N',
    title: 'Article N',
    description: 'This is Article N',
    url: '/article/n',
  },
  {
    eyeCatch: 'image3.png',
    category: 'O',
    title: 'Article O',
    description: 'This is Article O',
    url: '/article/o',
  },
  {
    eyeCatch: 'image1.png',
    category: 'P',
    title: 'Article P',
    description: 'This is Article P',
    url: '/article/p',
  },
  {
    eyeCatch: 'image2.png',
    category: 'Q',
    title: 'Article Q',
    description: 'This is Article Q',
    url: '/article/q',
  },
  {
    eyeCatch: 'image3.png',
    category: 'R',
    title: 'Article R',
    description: 'This is Article R',
    url: '/article/r',
  },
  {
    eyeCatch: 'image1.png',
    category: 'S',
    title: 'Article S',
    description: 'This is Article S',
    url: '/article/s',
  },
  {
    eyeCatch: 'image2.png',
    category: 'T',
    title: 'Article T',
    description: 'This is Article T',
    url: '/article/t',
  },
  {
    eyeCatch: 'image3.png',
    category: 'U',
    title: 'Article U',
    description: 'This is Article U',
    url: '/article/u',
  },
  {
    eyeCatch: 'image1.png',
    category: 'V',
    title: 'Article V',
    description: 'This is Article V',
    url: '/article/v',
  },
  {
    eyeCatch: 'image2.png',
    category: 'W',
    title: 'Article W',
    description: 'This is Article W',
    url: '/article/w',
  },
  {
    eyeCatch: 'image3.png',
    category: 'X',
    title: 'Article X',
    description: 'This is Article X',
    url: '/article/x',
  },
  {
    eyeCatch: 'image1.png',
    category: 'Y',
    title: 'Article Y',
    description: 'This is Article Y',
    url: '/article/y',
  },
  {
    eyeCatch: 'image2.png',
    category: 'Z',
    title: 'Article Z',
    description: 'This is Article Z',
    url: '/article/z',
  },
];
